default:
  image: amazoncorretto:17.0.8@sha256:eaa4ff4026b888b602b9cef6875a7b763ab4b3076f1257c14237bd31bea54167
  before_script:
    - ': before_script'
    - chmod +x gradlew
    - export GRADLE_USER_HOME=`pwd`/.gradle

# Static Application Security Testing (SAST) is a frequently used Application Security (AppSec) tool,
# which scans an application’s source, binary, or byte code.
# https://www.microfocus.com/en-us/what-is/sast
include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SAST_JAVA_VERSION: "17" # Required by SAST scanning

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - ': script'
    - ./gradlew check sonar
    - cat coverage-report/build/reports/jacoco/testCodeCoverageReport/html/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - coverage-report/build/reports/jacoco/testCodeCoverageReport/html/**
    reports:
      junit:
        - "**/build/test-results/test/TEST-*.xml"
    expire_in: 1 hour

build-package:
  stage: build
  script:
    - ': script'
    - ./gradlew build -x test
  artifacts:
    paths:
      - "**/build/libs/*.jar"
    expire_in: 1 hour

sonarcloud-check:
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ': script'
    - ./gradlew check sonar
  only:
    - merge_requests
    - main

pages:
  stage: deploy
  script:
    - echo 'Cleaning old pages'
    - rm -rf public
    - ls -la
    - mkdir -p public/jacoco-report && cp -r coverage-report/build/reports/jacoco/testCodeCoverageReport/html/* public/jacoco-report
    - echo 'Public directory content after copying files'
    - ls -la ./public
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - main
